apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftwebsite-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giftwebsite
  template:
    metadata:
      labels:
        app: giftwebsite
    spec:
      containers:
        - name: giftwebsite
          image: us.icr.io/sn-labs-blue1045/giftwebsite
          ports:
            - containerPort: 9000
      imagePullSecrets:
        - name: icr
---
apiVersion: v1
kind: Service
metadata:
  name: giftwebsite-service
spec:
  type: NodePort
  selector:
    app: giftwebsite
  ports:
    - port: 9000
      targetPort: 9000        
